//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealtyAgencyMLS.Admin.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealtyAgencyMLS.Admin.Resource.AppData", typeof(AppData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_AdminGetPropertyListing.
        /// </summary>
        public static string AdminGetPropertyListing {
            get {
                return ResourceManager.GetString("AdminGetPropertyListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://therealtyagencyqa.chetu.com.
        /// </summary>
        public static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added successfully!.
        /// </summary>
        public static string CreatedSuccess {
            get {
                return ResourceManager.GetString("CreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record updated successfully!.
        /// </summary>
        public static string DataUpdated {
            get {
                return ResourceManager.GetString("DataUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted successfully!.
        /// </summary>
        public static string DeletedSuccess {
            get {
                return ResourceManager.GetString("DeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting record!.
        /// </summary>
        public static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_AdminGetFeaturedListing.
        /// </summary>
        public static string eewwq {
            get {
                return ResourceManager.GetString("eewwq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Already Existed !.
        /// </summary>
        public static string ExistRecord {
            get {
                return ResourceManager.GetString("ExistRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while getting info from server!.
        /// </summary>
        public static string FetchError {
            get {
                return ResourceManager.GetString("FetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllCulture.
        /// </summary>
        public static string GetAllCulture {
            get {
                return ResourceManager.GetString("GetAllCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllFAQ.
        /// </summary>
        public static string GetAllFAQ {
            get {
                return ResourceManager.GetString("GetAllFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllGetAllPartners.
        /// </summary>
        public static string GetAllGetAllPartners {
            get {
                return ResourceManager.GetString("GetAllGetAllPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetFeaturedGalleryImages.
        /// </summary>
        public static string GetFeaturedGalleryImages {
            get {
                return ResourceManager.GetString("GetFeaturedGalleryImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetSingleFeaturedListingByPropertyId.
        /// </summary>
        public static string GetSingleFeaturedListingByPropertyId {
            get {
                return ResourceManager.GetString("GetSingleFeaturedListingByPropertyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetSingleFloorPlanImage.
        /// </summary>
        public static string GetSingleFloorPlanImage {
            get {
                return ResourceManager.GetString("GetSingleFloorPlanImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password!.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_IsExistFeaturedListingInfo.
        /// </summary>
        public static string IsExistFeaturedListingInfo {
            get {
                return ResourceManager.GetString("IsExistFeaturedListingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Project Data\Repository\RealtyAgencyMLS_V_1.0\RealtyAgencyMLS\RealtyAgencyMLS\wwwroot.
        /// </summary>
        public static string RootPath {
            get {
                return ResourceManager.GetString("RootPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrainingDocument.
        /// </summary>
        public static string TrainingDocument {
            get {
                return ResourceManager.GetString("TrainingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrainingVideo.
        /// </summary>
        public static string TrainingVideo {
            get {
                return ResourceManager.GetString("TrainingVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAgentByAppUserID.
        /// </summary>
        public static string usp_GetAgentByAppUserID {
            get {
                return ResourceManager.GetString("usp_GetAgentByAppUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAgentsListWithoutFilterd.
        /// </summary>
        public static string usp_GetAgentsListWithoutFilterd {
            get {
                return ResourceManager.GetString("usp_GetAgentsListWithoutFilterd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAgetntServiceById.
        /// </summary>
        public static string usp_GetAgetntServiceById {
            get {
                return ResourceManager.GetString("usp_GetAgetntServiceById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllAgetntCommercial.
        /// </summary>
        public static string usp_GetAllAgetntCommercial {
            get {
                return ResourceManager.GetString("usp_GetAllAgetntCommercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllAgetntPropertyManagement.
        /// </summary>
        public static string usp_GetAllAgetntPropertyManagement {
            get {
                return ResourceManager.GetString("usp_GetAllAgetntPropertyManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllBlogCategory.
        /// </summary>
        public static string usp_GetAllBlogCategory {
            get {
                return ResourceManager.GetString("usp_GetAllBlogCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllBlogs.
        /// </summary>
        public static string usp_GetAllBlogs {
            get {
                return ResourceManager.GetString("usp_GetAllBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllCompany.
        /// </summary>
        public static string usp_GetAllCompany {
            get {
                return ResourceManager.GetString("usp_GetAllCompany", resourceCulture);
            }
        }
        /// <summary>
       ///   Looks up a localized string similar to usp_GetAllCulture.
        /// </summary>
        public static string usp_GetAllCulture {
            get {
                return ResourceManager.GetString("usp_GetAllCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllGetAllThingsToDo.
        /// </summary>
        public static string usp_GetAllGetAllThingsToDo {
            get {
                return ResourceManager.GetString("usp_GetAllGetAllThingsToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllJoinTRAOffer.
        /// </summary>
        public static string usp_GetAllJoinTRAOffer {
            get {
                return ResourceManager.GetString("usp_GetAllJoinTRAOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllModule.
        /// </summary>
        public static string usp_GetAllModule {
            get {
                return ResourceManager.GetString("usp_GetAllModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllPermissions.
        /// </summary>
        public static string usp_GetAllPermissions {
            get {
                return ResourceManager.GetString("usp_GetAllPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllProductCategory.
        /// </summary>
        public static string usp_GetAllProductCategory {
            get {
                return ResourceManager.GetString("usp_GetAllProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllProducts.
        /// </summary>
        public static string usp_GetAllProducts {
            get {
                return ResourceManager.GetString("usp_GetAllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllTrainingSection.
        /// </summary>
        public static string usp_GetAllTrainingSection {
            get {
                return ResourceManager.GetString("usp_GetAllTrainingSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllTrainingVideos.
        /// </summary>
        public static string usp_GetAllTrainingVideos {
            get {
                return ResourceManager.GetString("usp_GetAllTrainingVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllUpComingEvents.
        /// </summary>
        public static string usp_GetAllUpComingEvents {
            get {
                return ResourceManager.GetString("usp_GetAllUpComingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllUsers.
        /// </summary>
        public static string usp_GetAllUsers {
            get {
                return ResourceManager.GetString("usp_GetAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllVehicle.
        /// </summary>
        public static string usp_GetAllVehicle {
            get {
                return ResourceManager.GetString("usp_GetAllVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetAllVehicleType.
        /// </summary>
        public static string usp_GetAllVehicleType {
            get {
                return ResourceManager.GetString("usp_GetAllVehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetEthicsAboutCompany.
        /// </summary>
        public static string usp_GetEthicsAboutCompany {
            get {
                return ResourceManager.GetString("usp_GetEthicsAboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_GetPropertyFirstPhotoName.
        /// </summary>
        public static string usp_GetPropertyFirstPhotoName {
            get {
                return ResourceManager.GetString("usp_GetPropertyFirstPhotoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_UpdateLastProperty.
        /// </summary>
        public static string usp_UpdateLastProperty {
            get {
                return ResourceManager.GetString("usp_UpdateLastProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all required fields correctly!.
        /// </summary>
        public static string ValidationFieldRequired {
            get {
                return ResourceManager.GetString("ValidationFieldRequired", resourceCulture);
            }
        }
    }
}
